logging:
  level:
    root: INFO
  file:
    name: ./log/messaging.log
  pattern:
    level: r=%X{r} ip=%X{ip} %5p
spring:
  application:
    name: messaging
  cassandra:
    keyspace-name: yourkeyspace
    contact-points: localhost
    port: 9042
server:
  port: 8080
  error:
    include-message: always
